restructure tasks

diff --git a/.devcontainer/custom_component_helper b/.devcontainer/custom_component_helper
--- a/.devcontainer/custom_component_helper
+++ b/.devcontainer/custom_component_helper
@@ -1,10 +1,26 @@
 #!/usr/bin/env bash
-echo "Copy configuration.yaml"
-cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml are missing!" exit 1
 
-echo "Copy the custom component"
-rm -R /config/custom_components/ || echo ""
-cp -r custom_components /config/custom_components/ || echo "Could not copy the custom_component" exit 1
+function StartHomeAssistant {
+  echo "Copy configuration.yaml"
+  cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml are missing!" exit 1
 
-echo "Start Home Assistant"
-hass -c /config
+  echo "Copy the custom component"
+  rm -R /config/custom_components/ || echo ""
+  cp -r custom_components /config/custom_components/ || echo "Could not copy the custom_component" exit 1
+
+  echo "Start Home Assistant"
+  hass -c /config
+}
+
+function UpdgradeHomeAssistantDev {
+  python -m pip install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev
+}
+
+function SetHomeAssistantVersion {
+  read -p 'Version: ' version
+  python -m pip install --upgrade homeassistant==$version
+}
+
+function HomeAssistantConfigCheck {
+  hass -c /config --script check_config
+}
